package com.appis.android.domain.orchestrator.stages

import android.content.Context
import com.appis.android.data.filesystem.FmsService
import com.appis.android.data.git.RepoManager
import dagger.hilt.android.qualifiers.ApplicationContext
import javax.inject.Inject

class SyncStage @Inject constructor(
    private val repoManager: RepoManager,
    private val fmsService: FmsService,
    @ApplicationContext private val context: Context
) {
    suspend fun execute(token: String, projectId: String, projectName: String, owner: String): Boolean {
        val repoName = projectName.lowercase().replace(" ", "-")
        // Try creating repo (ignore if exists)
        repoManager.createRepo(token, repoName, "Generated by Appis")
        
        val rootDir = fmsService.getProjectRoot(projectId)
        val fileMap = mutableMapOf<String, String>()
        
        rootDir.walkTopDown().forEach { file ->
            if (file.isFile) {
                val relativePath = file.relativeTo(rootDir).path
                val content = file.readText()
                fileMap[relativePath] = content
            }
        }

        // Inject Workflow
        try {
            val workflowContent = context.assets.open("android_build.yml").bufferedReader().use { it.readText() }
            fileMap[".github/workflows/android_build.yml"] = workflowContent
        } catch (e: Exception) {
            // Log error or ignore
        }
        
        return repoManager.pushChanges(
            token = token,
            owner = owner,
            repo = repoName,
            files = fileMap,
            message = "feat: Autonomous build via Appis"
        )
    }
}
